### ISSUE TITLE
Cannot query the value of property 'projectId' because it has no value available.

### ISSUE THREAD

**Issue by NyakoFox** [TheMrMilchmann/gradle-curseforge-publish#52]
My configuration is as follows:

```
curseforge {
    apiToken = env.CURSEFORGE_TOKEN.value
    publications {
        register("curseForge") {
            projectId = "570109"

            artifacts.register("main") {
                from(tasks.named("remapJar"))

                displayName = "VanitySlots 2.0.0+1.21.1"

                changelog {
                    content = file('../CHANGELOG.md').text
                }

                relations {
                    requiredDependency("fabric-api")
                    requiredDependency("accessories")
                    requiredDependency("forge-config-api-port-fabric")
                    optionalDependency("modmenu")
                }
            }
        }
    }
}
```

I'm doing a multiloader setup, so this is the fabric build.gradle. I have a slightly modified version in NeoForge's build.gradle, and that works fine, however the Fabric one doesn't, despite the projectId line being the same. My repo is [here](https://github.com/NyakoFox/VanitySlots) if you'd like to take a closer look.

**Comment by TheMrMilchmann** [comment]
> Cannot query the value of property 'projectId' because it has no value available.

This is usually an indication of a publication that's not configured. In your particular case, this happens because you are registering a new publication even though [a publication is preregistered for Fabric](https://github.com/TheMrMilchmann/gradle-curseforge-publish?tab=readme-ov-file#interoperability).

You can fix this issue by applying the following changes:

```diff
diff --git a/fabric/build.gradle b/fabric/build.gradle
index 20cbb20..0b9934e 100644
--- a/fabric/build.gradle
+++ b/fabric/build.gradle
@@ -8,12 +8,10 @@ plugins {
 curseforge {
     apiToken = env.CURSEFORGE_TOKEN.value
     publications {
-        register("curseForge") {
+        named("fabric") {
             projectId = "570109"
 
-            artifacts.register("main") {
-                from(tasks.named("remapJar"))
-
+            artifacts.named("main") {
                 displayName = "VanitySlots (Fabric) 2.0.0+1.21.1"
 
                 changelog {
```

Note that there is no automatically registered publication for the NeoForge Gradle plugin (ModDevGradle) you are using. This will be added in `0.7.0`.
